[project]
name = "smartphone-addiction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "fsspec>=2026.7.0",
    "joblib>=1.5.3",
    "jupyter>=1.1.1",
    "matplotlib>=3.11.1",
    "numpy>=2.5.1",
    "pandas>=3.0.5",
    "scikit-learn>=1.9.0",
    "scipy>=1.18.0",
    "streamlit>=1.61.1",
    "sweetviz>=2.3.3",
    "xgboost>=3.4.0",
]
